### ISSUE TITLE
Leak analysis for `addMeshToObjectArray`

### ISSUE THREAD

**Issue by deepfire** [lambdacube3d/lambdacube-gl#11]
While trying to compose a deterministically leak-free environment, I've stumbled upon another issue,
namely `addMeshToObjectArray`.  Let me explain.

The previous entity, `uploadMeshToGPU`, has returned objects that exibited following characteristics:
- they didn't pin memory on the Haskell side
- the memory pinned on the C side, was available to release by `disposeMesh`

This time, while `addMeshToObjectArray` calls `addObject`, which has an opposite,
going by name of `removeObject`, calling that _opposite_ doesn't lead to memory being released _entirely_:

`addMeshToObjectArray` with `removeObject` `addFinalizer`-attached: amortizedleak  ~= 2K/frame:
```
# frame gcmem delta mem/fr time/fr non-GC-time/fr
...
  669n 924k    2dK     2K/f  1.62ms, 0.28ms nonGC
  670n 927k    3dK     2K/f  1.62ms, 0.27ms nonGC
  671n 913k  -14dK     2K/f  1.64ms, 0.30ms nonGC
  672n 916k    3dK     2K/f  1.65ms, 0.30ms nonGC
  673n 918k    2dK     2K/f  1.66ms, 0.27ms nonGC
  674n 921k    3dK     2K/f  1.68ms, 0.27ms nonGC
  675n 923k    2dK     2K/f  1.68ms, 0.24ms nonGC
  676n 926k    3dK     2K/f  1.68ms, 0.24ms nonGC
  677n 928k    2dK     2K/f  1.68ms, 0.26ms nonGC
  678n 931k    3dK     2K/f  1.68ms, 0.27ms nonGC
  679n 933k    2dK     2K/f  1.69ms, 0.27ms nonGC
  680n 936k    3dK     2K/f  1.69ms, 0.27ms nonGC
  681n 938k    2dK     2K/f  1.67ms, 0.25ms nonGC
  682n 941k    3dK     2K/f  1.66ms, 0.29ms nonGC
  683n 927k  -14dK     2K/f  1.65ms, 0.25ms nonGC
  684n 930k    3dK     2K/f  1.64ms, 0.24ms nonGC
  685n 932k    2dK     2K/f  1.64ms, 0.25ms nonGC
  686n 935k    3dK     2K/f  1.65ms, 0.25ms nonGC
  687n 937k    2dK     2K/f  1.66ms, 0.26ms nonGC
```

Statistics gathered with `LCstress.hs` from https://github.com/deepfire/mood/blob/44a9b436f7237faaa9c009f1ba97691f19337f96/LCstress.hs#L124

**Comment by deepfire-pusher** [comment]
Fix in https://github.com/lambdacube3d/lambdacube-gl/pull/12

**Comment by ScottFreeCode** [comment]
Is this fixed?

**Comment by csabahruska** [comment]
Yes.
