### ISSUE TITLE
Render to texture is broken

### ISSUE THREAD

**Issue by NCrashed** [lambdacube3d/lambdacube-gl#5]
Hi, I had found that render to texture is not operational anymore (possible a regression or my bad) while I was reanimating my old projects with LambdaCube.

A minified example with the issue is located here: https://github.com/NCrashed/lc-test/tree/470b99ab79a083596b289ed18305b38b385e4715

The main issue that a texture created with `PrjImageColor` is substituted with any other texture that is loaded with `uploadTexture2DToGPU`.

See [main.lc line 39](https://github.com/NCrashed/lc-test/blob/470b99ab79a083596b289ed18305b38b385e4715/main.lc#L39), the normal mode when a frame buffer is rendered directly and bugged mode is when I try to render the frame via texture and window sized quad:
```
  in renderFrame $ displayQuad $ Texture2D windowSize . PrjImageColor $ cubeFrame -- that doesn't
  --in renderFrame cubeFrame -- that works
```

Normal mode:
![screenshot from 2017-01-25 16-37-23](https://cloud.githubusercontent.com/assets/2116167/22292519/16fe0aea-e325-11e6-9192-e557b5ded4a5.png)

Bugged mode:

![screenshot from 2017-01-25 16-37-11](https://cloud.githubusercontent.com/assets/2116167/22292507/08c8dafe-e325-11e6-8a9b-540af0a551d5.png)

**Comment by csabahruska** [comment]
It seems my "optimization" in lambdacube-gl messed it up.
It works with an earlier version: [lambdacube-gl-0.5.1.2](http://hackage.haskell.org/package/lambdacube-gl-0.5.1.2)

**Comment by NCrashed** [comment]
Thank you, it is good as temporary solution, but I don't want to stay on old version forever. I'll will be very happy if the issue is resolved someday :) .

**Comment by NCrashed** [comment]
Thank you!

**Comment by NCrashed** [comment]
Yay! Everything is operational now. Thank you very much!
