### ISSUE TITLE
Question: pipeline for a dynamically varying set of dynamically updated textures

### ISSUE THREAD

**Issue by deepfire** [lambdacube3d/lambdacube-gl#7]
Context:
- 2.5D scene graph UI
- elements are surfaces dynamically drawn into with Cairo -- not every frame, but often
- the set of elements is varying

Questions:
1. what would be the right Lambdacube pipeline for that use case?
2. could such a pipeline be formulated as an extension of `Graphics.lc` in `lambdacube-quake3`?

**Comment by csabahruska** [comment]
Can you describe the use cases with more details?

**Comment by deepfire** [comment]
* *scene* is composed of:
  * a dynamically varying set of *elements*, on the *foreground*:
    * the total set of elements is subject to frequent changes (so pipeline recompilation is not an option)
    * visibility of an element determined by viewport X/Y, and obscures-obscured relationship between elements
    * performance target is, roughly, 100s of visible elements at 60fps
    * the elements on the *foreground* are partitioned in two parts:
      * the orthogonally-projected screen pixel<->texture pixel *foreground front*, with tens of elements
      * the perspective-projected classically shaded *middle-ground*, so to speak, with hundreds of elements
  * *optionally*, and not essentially to the main question, a complex scene on the background (a BSP-based QuakeIII level is a good start)
* a single *element* is, basically a flat *rectangle* with a *texture*, with the following properties:
  * the *rectangle* is subject to changes in dimensions and position
  * the *texture* is subject to frequent, potentially significant change both in dimensions and in content, which is supplied with a variation on `uploadTexture2DToGPU'` (and produced using Cairo, but that is tangential)
  * purpose of an element is to simulate a small window with text and decorations -- so non-blurring for the *foreground front* elements is important

**Comment by deepfire** [comment]
Speaking comparatively:
* `lambdacube-quake3` pipeline (for `q3dm`, for example) has:
  * ~150 static materials, which corresponds to ~250 different shader stages 
  * many of which are similar, only differing in texture, so maybe ~20-30 (?) materials differing in properties other than texture
* *if* we naively apply the same `GLSlot`-per-material model as in `lambdacube-quake3` to the use case described above -- even assuming we come up with a `GLSlot` manager to load/unload visible/invisible *elements* (which is probably inevitable anyway), then:
  1. we potentially get even more materials and stages -- and I say more, because we would like to upload more of the elements (more than the ~100s potentially visible) to the GPU, to decrease load/unload churn
  2. ..and now they _all_ are _only_ differing in texture dimensions & contents

..and it is the combination of №1 and №2, which has led me to asking the question.

**Comment by csabahruska** [comment]
As I understand, you would like to display lots of rectangles with a unique texture on each.
And the rectangles position and size is varying and also the number of rectangles.
Is this accurate?

**Comment by deepfire** [comment]
Yes, very much so!

**Comment by csabahruska** [comment]
In that case, the pipeline will be very simple, a basic texture mapping render function will do.
i.e. [hello.lc](https://github.com/lambdacube3d/lambdacube-gl/blob/master/examples/hello.lc) from [getting started](http://lambdacube3d.com/getting-started).
You can create each rectangle instance with [addMeshToObjectArray](http://hackage.haskell.org/package/lambdacube-gl-0.5.2.3/docs/LambdaCube-GL-Mesh.html#v:addMeshToObjectArray) and then set the object's uniform values by [updateObjectUniforms](http://hackage.haskell.org/package/lambdacube-gl-0.5.2.3/docs/LambdaCube-GL.html#v:updateObjectUniforms).

Here is a [use case](https://github.com/lambdacube3d/lambdacube-gl/blob/master/examples/HelloOBJ.hs#L83-L88) from HelloOBJ.hs.

**Comment by deepfire** [comment]
Thank you a lot!

I've never really got into GL programming before, and so I'm only just learning the trade, and my intuitions of what to focus on are often way off.. : -)
