### ISSUE TITLE
Texture projection/shading infelicity

### ISSUE THREAD

**Issue by deepfire** [lambdacube3d/lambdacube-gl#8]
It seems that I have encountered texture distortion issues, which appear to be related to projection precision.
What I'm trying to do:
* trivial geometry:
```
MD3.Surface
{ srName      = "canvasSurface"
, srShaders   = V.fromList  [MD3.Shader {shIndex = 0, shName = SB.pack cvMaterial }]
, srTriangles = SV.fromList [0,2,1,0,1,3]
, srTexCoords = SV.fromList [ Vec2 0 1, Vec2 1 0
                            , Vec2 0 0, Vec2 1 1]
, srXyzNormal = V.singleton ( SV.fromList [Vec3 0 dy 0, Vec3 dx 0 0, Vec3 0 0 0, Vec3 dx dy 0]
                            , SV.fromList [Vec3 0  0 n, Vec3  0 0 n, Vec3 0 0 n, Vec3  0  0 n] ) }
```
* flat-projected texture
* ..which I'm trying to achieve using either a `glOrtho` matrix (as per OpenGL manpage), *or* using a more primitive aspect-correction matrix
* then I'm resizing the lambdacube-drawn window, and watching how the image fluctuates between distorted and non-distorted state, depending on the window aspect rate:
  * https://github.com/deepfire/mood/blob/master/lc-textured-distortion.png
  * https://github.com/deepfire/mood/blob/master/lc-textured-okay.png
* the `lc-textured-distortion.png` picture corresponds to a projection due to `glOrtho` matrix:
```
ortho :: Float  -- ^ Left
      -> Float  -- ^ Right
      -> Float  -- ^ Bottom
      -> Float  -- ^ Top
      -> Float  -- ^ Near
      -> Float  -- ^ Far
      -> Mat4
ortho l r b t n f =
    Mat4 (Vec4 (2/(r-l))    0          0       (-(r+l)/(r-l)))
         (Vec4   0        (2/(t-b))    0       (-(t+b)/(t-b)))
         (Vec4   0          0       (-2/(f-n)) (-(f+n)/(f-n)))
         (Vec4   0          0          0              1)
```
I have managed to reduce (but not entirely eliminate) the distortion by simplifying the matrix to:
```
screenM :: Int -> Int -> Mat4
screenM w h =
  Mat4 (Vec4 (1/fw)  0     0 0)
       (Vec4  0     (1/fh) 0 0)
       (Vec4  0      0     1 0)
       (Vec4  0      0     0 0.5)
  where (fw, fh) = (fromIntegral w, fromIntegral h)
```

**Comment by deepfire** [comment]
My instinct was to try to use `Double` for the canvas geometry, but alas, it appears that `Double` is unknown to `lambdacube-compiler`.. : -)

**Comment by csabahruska** [comment]
OpenGL 3.3 does not support `double` types in shaders. The best you can do is to create the matrix in the CPU side of the app in Haskell and pass the matrix to the render function as a uniform.

**Comment by deepfire** [comment]
You probably refer to disabling GPU-side coordinate transforms, like those performed by `mkVertexShader` in `Graphics.lc`: https://github.com/lambdacube3d/lambdacube-quake3/blob/master/lc/Graphics.lc#L215-L225

I see what you mean..  Guessing that a transform-less path for flat surfaces is the way, indeed..

Thank you!
